# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empty', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('Level', models.TextField(choices=[('major', 'רב סרן'), ('lieutenant colonel', 'סגן אלוף'), ('colonel', 'אלוף משנה'), ('brigadier general', 'תת אלוף'), ('lieutenant general', 'אלוף'), ('chief of general staff', 'רב אלוף'), ('VCTech', 'טכנאי מערכת'), ('special privilege', 'הרשאה מיוחדת')])),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('pikud', models.CharField(choices=[('North', 'צפון'), ('Center', 'מרכז'), ('South', 'דרום'), ('Homefront', 'העורף'), ('DeepOp', 'העומק')], max_length=30)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('status', models.TextField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('C', 'Completed')], default='pending approval')),
                ('VC_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_time', models.DateTimeField()),
                ('starting_time', models.DateTimeField()),
                ('participants', models.TextField()),
            ],
        ),
    ]
