# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCU_ip', models.GenericIPAddressField()),
                ('DMA_ip', models.GenericIPAddressField()),
                ('RM_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pikud', models.CharField(choices=[('North', 'צפון'), ('Center', 'מרכז'), ('South', 'דרום'), ('Homefront', 'העורף'), ('DeepOp', 'העומק')], max_length=30)),
                ('title', models.CharField(max_length=60)),
                ('name', models.CharField(max_length=60)),
                ('id_number', models.CharField(default='1', max_length=20, unique=True)),
                ('level', models.CharField(choices=[('major', 'רב סרן'), ('lieutenant colonel', 'סגן אלוף'), ('colonel', 'אלוף משנה'), ('brigadier general', 'תת אלוף'), ('lieutenant general', 'אלוף'), ('chief of general staff', 'רב אלוף'), ('VCTech', 'טכנאי מערכת'), ('special privilege', 'הרשאה מיוחדת')], max_length=30)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rmxrules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkal', models.IntegerField()),
                ('tzameret_a', models.IntegerField()),
                ('tzameret_a_redundant', models.IntegerField()),
                ('tzameret_b', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='VCallcenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_callcenter', models.CharField(max_length=60)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('NW', 'Not Working'), ('W', 'Working'), ('M', 'Maintenance'), ('R', 'Reserved'), ('DNR', 'Does Not Respond')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VCkit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_kit', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField()),
                ('pikud', models.CharField(choices=[('North', 'צפון'), ('Center', 'מרכז'), ('South', 'דרום'), ('Homefront', 'העורף'), ('DeepOp', 'העומק')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='VCversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VSX_version', models.CharField(max_length=100)),
                ('HDX_version', models.CharField(max_length=100)),
                ('GROUP_version', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='VideoCall',
            fields=[
                ('status', models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('C', 'Completed')], default='P', max_length=20)),
                ('VC_id', models.CharField(default=uuid.uuid4, editable=False, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('request_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('starting_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('ending_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('participants', models.ManyToManyField(default=None, related_name='participants', to='callcenter.Profile')),
                ('vc_head', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vc_head', to='callcenter.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='vcallcenter',
            name='current_videocalls',
            field=models.ManyToManyField(to='callcenter.VideoCall'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vckits',
            field=models.ManyToManyField(blank=True, to='callcenter.VCkit'),
        ),
    ]
