# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-11 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fake',
        ),
        migrations.AlterField(
            model_name='profile',
            name='Level',
            field=models.CharField(choices=[('major', 'רב סרן'), ('lieutenant colonel', 'סגן אלוף'), ('colonel', 'אלוף משנה'), ('brigadier general', 'תת אלוף'), ('lieutenant general', 'אלוף'), ('chief of general staff', 'רב אלוף'), ('VCTech', 'טכנאי מערכת'), ('special privilege', 'הרשאה מיוחדת')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name='profile',
            name='title',
            field=models.CharField(max_length=60),
        ),
        migrations.RemoveField(
            model_name='videocall',
            name='participants',
        ),
        migrations.AddField(
            model_name='videocall',
            name='participants',
            field=models.ManyToManyField(to='callcenter.Profile'),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('C', 'Completed')], default='pending approval', max_length=20),
        ),
    ]
