# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-12 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0003_auto_20170211_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCallcenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_callcenter', models.CharField(max_length=60)),
                ('capacity', models.IntegerField()),
                ('status', models.CharField(choices=[('NW', 'Not Working'), ('W', 'Working'), ('M', 'Maintenance'), ('R', 'Reserved'), ('DNR', 'Does Not Respond')], max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='Level',
            new_name='level',
        ),
        migrations.AddField(
            model_name='videocall',
            name='vc_head',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='vc_head', to='callcenter.Profile'),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='participants',
            field=models.ManyToManyField(related_name='participants', to='callcenter.Profile'),
        ),
        migrations.AddField(
            model_name='vcallcenter',
            name='current_videocalls',
            field=models.ManyToManyField(to='callcenter.VideoCall'),
        ),
    ]
