# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0004_auto_20170212_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCkit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_kit', models.CharField(max_length=30)),
                ('ip', models.GenericIPAddressField()),
                ('pikud', models.CharField(choices=[('North', 'צפון'), ('Center', 'מרכז'), ('South', 'דרום'), ('Homefront', 'העורף'), ('DeepOp', 'העומק')], max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='id_number',
            field=models.CharField(default=0, max_length=20, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='videocall',
            name='ending_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='participants',
            field=models.ManyToManyField(default=None, related_name='participants', to='callcenter.Profile'),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='request_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='starting_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved'), ('R', 'Rejected'), ('C', 'Completed')], default='P', max_length=20),
        ),
        migrations.AlterField(
            model_name='videocall',
            name='vc_head',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='vc_head', to='callcenter.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='vckits',
            field=models.ManyToManyField(to='callcenter.VCkit'),
        ),
    ]
