# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0005_auto_20170214_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiUse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MCU_ip', models.GenericIPAddressField()),
                ('DMA_ip', models.GenericIPAddressField()),
                ('RM_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='vckits',
            field=models.ManyToManyField(blank=True, to='callcenter.VCkit'),
        ),
    ]
