# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0006_auto_20170214_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCversion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('VSX_version', models.CharField(max_length=100)),
                ('HDX_version', models.CharField(max_length=100)),
                ('GROUP_version', models.CharField(max_length=100)),
            ],
        ),
    ]
