# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0007_vcversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rmxrules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matkal', models.IntegerField()),
                ('tzameret_a', models.IntegerField()),
                ('tzameret_a_redundant', models.IntegerField()),
                ('tzameret_b', models.IntegerField()),
            ],
        ),
    ]
