# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-14 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callcenter', '0008_rmxrules'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='id_number',
            field=models.CharField(default='1', max_length=20, unique=True),
        ),
    ]
